### ISSUE TITLE
Dark Exchange is not finding all identities or otherwise connecting to the network.

### ISSUE THREAD

**Issue by macourtney** [macourtney/Dark-Exchange#2]
Dark Exchange is not finding all identities or otherwise connecting to the network.

**Comment by darkgamer** [comment]
Did you install i2p, if you did is it running? run it as user not as root or admin if on windows and it should connect

**Comment by macourtney** [comment]
Yes, i2p is installed and running. Otherwise, there would be an exception. The issue seems to have to do with i2p being slow, and Dark Exchange giving up too easily. I have a fix I'll check for this issue soon.

**Comment by macourtney** [comment]
Dark Exchange will now make several attempts and wait longer before timing out. Also, each time you start Dark Exchange, it will try to download all of the latest peers in the system.
